platform :ios, '14.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Runner
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
